// GENERATED by tool/embed.dart from viewer/index.html. Do not edit.
// Run `dart run tool/embed.dart` after changing the viewer.

/// The viewer page, as shipped.
const String viewerHtml = r'''
<!doctype html><html lang="es"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mockups</title>
<style>
:root{--ink:#1A1B25;--ink2:#6E7087;--bg:#ececed;--pri:#5457CD;--lateral:264px;}
*{box-sizing:border-box}
/* The author rules below set display on links and buttons; keep the hidden
   attribute winning (PDF link, Web heading, help rows). */
[hidden]{display:none!important}
body{margin:0;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif;color:var(--ink);background:var(--bg);overflow:hidden;height:100vh}

/* One screen at a time, full height: the phone of the current step starts at
   the top edge, with no frame around it. */
.lienzo{padding:0}
.lienzo iframe{display:block;width:100%;max-width:460px;margin:0 auto;border:0;overflow:hidden}
/* Message shown when the manifest is missing or broken. */
.lienzo .aviso{max-width:460px;margin:40px auto;padding:0 20px;color:var(--ink2);font-size:14px}
.lienzo .aviso code{font:12px ui-monospace,Menlo,monospace;background:#fff;padding:2px 6px;border-radius:6px}

/* The desktop sidebar: flows, PDF and the comment box, always visible. On
   mobile it does not exist; the floating buttons rule there. */
#lateral{display:none}
@media(min-width:900px){
  #lateral{display:flex;flex-direction:column;position:fixed;left:0;top:0;bottom:0;width:var(--lateral);background:#fff;border-right:1px solid #0000000f;padding:18px 14px 14px;z-index:9000}
  #lateral h1{margin:0 4px 14px;font-size:15.5px}
  #lateral nav{flex:1 1 auto;min-height:0;overflow-y:auto}
  #lateral h1,#lateral .raya,#lateral .pdf,#coment-lateral{flex-shrink:0}
  #lateral nav button,#lateral .pdf{display:flex;align-items:center;gap:10px;width:100%;padding:10px 12px;border:0;background:none;border-radius:12px;font:inherit;font-size:14px;color:var(--ink);text-decoration:none;cursor:pointer;text-align:left}
  #lateral nav button:hover,#lateral .pdf:hover{background:#f1f1f6}
  #lateral nav button.activo{color:var(--pri);font-weight:700;background:#f1f1fb}
  #lateral svg{width:16px;height:16px;flex:none;color:var(--ink2)}
  #lateral nav button.activo svg{color:var(--pri)}
  #lateral nav .paso-lateral{margin-left:auto;font-size:12px;color:var(--ink2);font-weight:600}
  #lateral .raya{height:1px;background:#ededf3;margin:8px 6px}
  /* The tree: "App" (the flows, step by step) and "Web" (desktop pages and
     plain links, no steps: they open in a new tab because they have no
     .frame the phone viewer can measure). */
  #lateral .grupo-titulo{margin:10px 6px 2px;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--ink2)}
  #lateral .grupo-web{flex:0 0 auto}
}
/* The same "App"/"Web" tree in the mobile menu (outside the media query: the
   mobile menu lives hidden on desktop, not removed). */
#menu .grupo-titulo{margin:8px 14px 2px;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--ink2)}
/* A flow row: the flow button plus an optional small "Spec" link. */
.fila{display:flex;align-items:center}
.fila>button{flex:1 1 auto;min-width:0}
.fila>.spec{flex:none;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--ink2);text-decoration:none;padding:6px 8px;border-radius:8px}
.fila>.spec:hover{background:#f1f1f6;color:var(--pri)}
@media(min-width:900px){
  .lienzo{margin-left:var(--lateral)}
  /* The buttons live in the sidebar: the floating ones covered the UI. */
  .fabs{display:none!important}
  #lateral-nav{display:flex;align-items:center;gap:8px;margin:0 4px 10px}
  #lateral-nav button{width:38px;height:38px;border-radius:50%;border:1px solid #e2e2ea;background:#fff;color:var(--pri);cursor:pointer;display:grid;place-items:center;padding:0}
  #lateral-nav button:hover{background:#f1f1f6}
  #lateral-nav button svg{width:17px;height:17px}
  #lateral-nav .paso{flex:1;text-align:center;font-size:12.5px;font-weight:700;color:var(--ink2)}
  #menu{display:none!important}
  /* The box lives inside the sidebar: static, always open. The double
     selector beats the base position:fixed rule, which comes later. */
  #coment-lateral #coment{position:static;display:block;width:auto;box-shadow:none;border:1px solid #ededf3;margin-top:8px}
  /* Keep the flow list visible: a short comment box and a capped Web group on desktop. */
  #coment-lateral #coment textarea{min-height:96px}
  #lateral .grupo-web{max-height:34vh;overflow-y:auto}
}

/* The three floating buttons (on desktop two remain: the menu lives in the
   sidebar). They can be MOVED: press and hold, then drag. */
.fabs{position:fixed;left:50%;transform:translateX(-50%);bottom:18px;display:flex;gap:16px;z-index:10001;touch-action:none;user-select:none;-webkit-user-select:none;-webkit-touch-callout:none}
.fabs.arrastrando .fab{transform:scale(1.06);box-shadow:0 12px 30px #1a1b2566}
.fab{width:54px;height:54px;border-radius:50%;border:0;cursor:pointer;display:grid;place-items:center;background:#fff;color:var(--pri);box-shadow:0 6px 18px #1a1b2540,0 1px 3px #1a1b2526}
.fab svg{width:22px;height:22px}
.fab:active{transform:scale(.95)}
.fab.principal{background:var(--pri);color:#fff;box-shadow:0 8px 20px #5457cd66}
/* The current step lives in the menu button ("2/4"). */
.fab.principal .paso{font-size:14.5px;font-weight:700;letter-spacing:.02em}

/* The menu (mobile): a floating sheet above the buttons. */
#menu{position:fixed;left:50%;transform:translateX(-50%);bottom:86px;z-index:10001;background:#fff;border-radius:18px;box-shadow:0 16px 48px #1a1b2559;padding:8px;min-width:250px;display:none}
#menu.abierto{display:block}
#menu a,#menu button{display:flex;align-items:center;gap:10px;width:100%;padding:11px 14px;border:0;background:none;border-radius:12px;font:inherit;font-size:14.5px;color:var(--ink);text-decoration:none;cursor:pointer;text-align:left}
#menu a:hover,#menu button:hover{background:#f1f1f6}
#menu .fila>.spec{width:auto;padding:6px 10px}
#menu .activo{color:var(--pri);font-weight:700}
#menu .raya{height:1px;background:#ededf3;margin:6px 8px}
#menu svg{width:16px;height:16px;flex:none;color:var(--ink2)}
#menu .activo svg{color:var(--pri)}

/* The comment box: small, for the screen being looked at. On mobile it floats
   above the buttons and opens with the menu; on desktop it lives at the foot
   of the sidebar, always open. It saves by itself to comentarios/index.md,
   under one heading per screen. */
#coment{position:fixed;z-index:10001;background:#fff;border-radius:16px;box-shadow:0 16px 48px #1a1b2559;padding:10px 12px;width:min(400px,calc(100vw - 24px));display:none}
#coment.abierto{display:block}
#coment header{display:flex;align-items:baseline;gap:8px;margin:0 2px 7px;font-size:12.5px;font-weight:700}
#coment header .estado{margin-left:auto;font-weight:400;font-size:11px;color:var(--ink2);white-space:nowrap}
#coment textarea{display:block;width:100%;min-height:230px;max-height:480px;resize:vertical;border:1px solid #e2e2ea;border-radius:10px;padding:10px 12px;font:14px/1.5 inherit;font-family:inherit;color:var(--ink);outline:none;background:#fafafc}
#coment textarea:focus{border-color:var(--pri)}

/* The shortcut help: ? opens and closes it. */
#ayuda{position:fixed;inset:0;z-index:10002;background:#1a1b2580;display:none;align-items:center;justify-content:center;padding:16px}
#ayuda.abierto{display:flex}
#ayuda .tarjeta{background:#fff;border-radius:18px;box-shadow:0 24px 64px #1a1b2566;padding:20px 22px;width:min(430px,100%);max-height:85vh;overflow-y:auto}
#ayuda h2{margin:0 0 12px;font-size:16px}
#ayuda table{width:100%;border-collapse:collapse;font-size:13.5px}
#ayuda td{padding:6px 4px;border-top:1px solid #f1f1f4;vertical-align:top}
#ayuda td:first-child{white-space:nowrap;padding-right:14px}
#ayuda kbd{display:inline-block;min-width:20px;text-align:center;padding:2px 6px;border:1px solid #d9dbe6;border-bottom-width:2px;border-radius:6px;background:#fafafc;font:12px ui-monospace,Menlo,monospace;color:var(--ink)}
#ayuda .nota{margin:12px 2px 0;font-size:12px;color:var(--ink2)}
</style>
</head><body>

<aside id="lateral">
  <h1 id="lateral-titulo">Mockups</h1>
  <div id="lateral-nav">
    <button id="lat-atras" accesskey="a" title="Anterior (accesskey A)" aria-label="Pantalla anterior">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
    </button>
    <span class="paso" id="lat-paso"></span>
    <button id="lat-sig" accesskey="s" title="Siguiente (accesskey S)" aria-label="Pantalla siguiente">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
    </button>
  </div>
  <p class="grupo-titulo">App</p>
  <nav id="lateral-flujos"></nav>
  <p class="grupo-titulo" id="lateral-web-titulo" hidden>Web</p>
  <div class="grupo-web" id="lateral-web"></div>
  <div class="raya"></div>
  <a class="pdf" id="lat-pdf" accesskey="d" hidden href="#" target="_blank" rel="noopener" title="Descargar PDF (accesskey D)">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="12" y1="12" x2="12" y2="17"/><polyline points="9.5 14.5 12 17 14.5 14.5"/></svg>
    Descargar PDF de revisión
  </a>
  <div id="coment-lateral"></div>
</aside>

<div class="lienzo" id="lienzo"></div>

<div id="menu">
  <p class="grupo-titulo">App</p>
  <div id="menu-flujos"></div>
  <p class="grupo-titulo" id="menu-web-titulo" hidden>Web</p>
  <div id="menu-web"></div>
  <div class="raya" id="menu-pdf-raya" hidden></div>
  <a id="menu-pdf" hidden href="#" target="_blank" rel="noopener">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="12" y1="12" x2="12" y2="17"/><polyline points="9.5 14.5 12 17 14.5 14.5"/></svg>
    Descargar PDF de revisión
  </a>
</div>

<div id="coment">
  <header><span>💬</span><span id="coment-clave"></span><span class="estado" id="coment-estado"></span></header>
  <textarea id="coment-texto" accesskey="c" placeholder="Comentario de esta pantalla…" spellcheck="false" title="Comentar esta pantalla (accesskey C)"></textarea>
</div>

<div id="ayuda" role="dialog" aria-label="Atajos de teclado">
  <div class="tarjeta">
    <h2>Atajos de teclado</h2>
    <table>
      <tr><td><kbd>←</kbd> <kbd>→</kbd></td><td>pantalla anterior / siguiente</td></tr>
      <tr><td><kbd>⌫</kbd></td><td>atrás (vuelve a la pantalla que abrió esta)</td></tr>
      <tr><td><kbd>Enter</kbd></td><td>tocar el Continuar de la pantalla visible</td></tr>
      <tr id="ayuda-flujos"><td><kbd>1</kbd>…<kbd id="ayuda-n">9</kbd></td><td>saltar a un flujo</td></tr>
      <tr><td><kbd>E</kbd></td><td>ver / ocultar validaciones</td></tr>
      <tr><td><kbd>O</kbd></td><td>tema claro / oscuro</td></tr>
      <tr><td><kbd>C</kbd></td><td>comentar esta pantalla</td></tr>
      <tr><td><kbd>M</kbd></td><td>menú (móvil)</td></tr>
      <tr id="ayuda-pdf" hidden><td><kbd>D</kbd></td><td>descargar el PDF de revisión</td></tr>
      <tr><td><kbd>?</kbd></td><td>esta ayuda</td></tr>
      <tr><td><kbd>Esc</kbd></td><td>cerrar</td></tr>
    </table>
    <p class="nota">Los mismos controles llevan <b>accesskey</b> (A/S anterior-siguiente, 1–9, E, C, D, M): en Mac se activan con <kbd>⌃</kbd>+<kbd>⌥</kbd>+tecla; en Windows/Linux con <kbd>Alt</kbd> (+<kbd>Shift</kbd> en Firefox).</p>
  </div>
</div>

<div class="fabs">
  <button class="fab" id="atras" title="Anterior (accesskey A)" aria-label="Pantalla anterior">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
  </button>
  <button class="fab principal" id="menu-btn" accesskey="m" title="Menú (accesskey M)" aria-label="Menú" aria-expanded="false">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><line x1="4" y1="7" x2="20" y2="7"/><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="17" x2="20" y2="17"/></svg>
  </button>
  <button class="fab" id="siguiente" title="Siguiente (accesskey S)" aria-label="Pantalla siguiente">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
  </button>
</div>

<script>
// The app-like viewer: one screen (one phone) at a time. Previous/Next walk
// the screens of a flow and cross into the neighbour flow at the edges. On
// mobile the floating menu switches flows, opens the PDF and brings the
// comment box; on desktop all of that lives in the sidebar.
//
// Nothing project-specific lives here. Everything comes from mockups.json,
// fetched from the same directory as this page:
//   { "title": "...", "flows": [{id, title, src, spec?}],
//     "web": [{title, src}], "links": [{title, href}], "pdf": "..." }
(function () {
  var lienzo = document.getElementById("lienzo");

  function fallo(msg) {
    var p = document.createElement("div");
    p.className = "aviso";
    p.innerHTML = msg;
    lienzo.appendChild(p);
  }

  // The manifest is fetched fresh every time: a cached copy would hide a flow
  // that was just added.
  fetch("mockups.json", { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (m) {
      var err = validar(m);
      if (err) throw new Error(err);
      iniciar(m);
    })
    .catch(function (e) {
      fallo(
        "No se pudo cargar <code>mockups.json</code> junto a este visor: " +
          String(e.message || e) +
          ". El visor necesita un servidor (no funciona abriendo el archivo)."
      );
    });

  // A quick shape check so a broken manifest fails with a readable message.
  function validar(m) {
    if (!m || typeof m !== "object") return "no es un objeto JSON";
    if (!Array.isArray(m.flows) || m.flows.length === 0) return "falta la lista flows";
    for (var i = 0; i < m.flows.length; i++) {
      var f = m.flows[i];
      if (!f || !f.id || !f.title || !f.src) return "flows[" + i + "] necesita id, title y src";
    }
    return null;
  }

  function iniciar(manifest) {
    var TITULO = manifest.title || "Mockups";
    var FLUJOS = manifest.flows.map(function (f) {
      return { id: String(f.id), titulo: String(f.title), src: String(f.src), spec: f.spec ? String(f.spec) : null };
    });
    var WEB = (manifest.web || []).map(function (w) {
      return { titulo: String(w.title), href: String(w.src) };
    });
    var LINKS = (manifest.links || []).map(function (l) {
      return { titulo: String(l.title), href: String(l.href) };
    });
    var PDF = manifest.pdf ? String(manifest.pdf) : null;

    document.title = TITULO;
    document.getElementById("lateral-titulo").textContent = TITULO;

    // The phones inside each page: .frame in most of them; some pages build
    // theirs with utility classes, hence the second selector.
    var SEL = '.frame, [class*="h-[844px]"]';

    var menu = document.getElementById("menu");
    var menuBtn = document.getElementById("menu-btn");
    var fabs = document.querySelector(".fabs");
    var HAMBURGUESA = menuBtn.innerHTML;
    var flujo = 0, pantalla = 0;
    // Error review mode: paints the forms with their invalid states.
    var conErrores = false;
    function alternarErrores() {
      conErrores = !conErrores;
      for (var j in marcos) {
        var d = marcos[j].f.contentDocument;
        if (d && d.body) d.body.classList.toggle("mostrar-errores", conErrores);
        medir(marcos[j]);
      }
      pintarMenu();
      pintarLateral();
    }
    // Dark theme of the mockups: remembered between visits.
    var oscuro = localStorage.getItem("mockups-oscuro") === "1";
    function alternarOscuro() {
      oscuro = !oscuro;
      localStorage.setItem("mockups-oscuro", oscuro ? "1" : "0");
      for (var j in marcos) {
        var d = marcos[j].f.contentDocument;
        if (d && d.body) d.body.classList.toggle("modo-oscuro", oscuro);
      }
      pintarMenu();
      pintarLateral();
    }
    var esEscritorio = matchMedia("(min-width:900px)");

    // One iframe per flow, created the first time it is visited. On load it
    // gets the full-screen outfit injected: no page padding, no rounded frame
    // on a real phone. It should look like the app.
    var marcos = {};
    function marco(i, listo) {
      var m = marcos[i];
      if (m) { m.cargado ? listo(m) : m.pendientes.push(listo); return; }
      var f = document.createElement("iframe");
      f.setAttribute("scrolling", "no");
      f.title = FLUJOS[i].titulo;
      f.style.display = "none";
      m = marcos[i] = { f: f, cargado: false, pendientes: [listo] };
      f.addEventListener("load", function () {
        var st = m.f.contentDocument.createElement("style");
        st.textContent =
          "html,body{height:100%}" +
          "body{padding:0!important;margin:0!important;gap:0!important;overflow:hidden}" +
          '.frame,[class*="h-[844px]"]{margin:0 auto!important;height:100%!important;min-height:0!important}' +
          // The phone measures the window and the content scrolls INSIDE,
          // like a real app: the column fills the frame and its scroll areas
          // scroll again (the CTA and the bars stay fixed).
          ".frame>div:first-child{height:100%!important;min-height:0!important}" +
          '[class*="overflow-y-auto"]:not([class*="overflow-x-auto"]),.frame-scroll:not([class*="overflow-x-auto"]),.scroll{overflow-y:auto!important;height:100%!important}' +
          // Form error states: off until the menu turns them on
          // (body.mostrar-errores).
          ".err{display:none}" +
          "body.mostrar-errores .err{display:block!important}" +
          "body.mostrar-errores .campo{border-color:#E5484D!important}" +
          // Dark theme: the palette variables change and the white surfaces
          // go off; the rest (text, icons) already dresses with var().
          "body.modo-oscuro{--bg:#12131B;--ink:#ECEDF2;--ink-2:#A5A7B6;--primary-soft:#2B2C49;background:#12131B!important}" +
          'body.modo-oscuro [class*="bg-white"]{background:#1C1D28!important}' +
          "body.modo-oscuro .border-gray-100{border-color:#2A2B36!important}" +
          "body.modo-oscuro .divide-gray-100>*{border-color:#2A2B36!important}" +
          'body.modo-oscuro [style*="border-color:#f1f1f4"],body.modo-oscuro [style*="border-color:#eceef4"],body.modo-oscuro [style*="border-color:#ececed"],body.modo-oscuro [style*="#d9dbe6"]{border-color:#33344263!important}' +
          'body.modo-oscuro [style*="background:#eceef4"]{background:#262735!important}' +
          'body.modo-oscuro [style*="background:#f1f1f4"]{background:#12131B!important}' +
          'body.modo-oscuro [style*="background:#FCF1DF"]{background:#3A2E17!important}' +
          'body.modo-oscuro [style*="background:#FDEBEC"]{background:#3A1D20!important}' +
          'body.modo-oscuro [style*="background:#E3F4EB"]{background:#173226!important}' +
          'body.modo-oscuro svg [fill="#1A1B25"]{fill:#ECEDF2}' +
          'body.modo-oscuro svg [stroke="#E9E9FB"]{stroke:#2B2C49}' +
          "@media(max-width:480px){" +
          '.frame,[class*="h-[844px]"]{width:100%!important;border-radius:0!important;box-shadow:none!important}' +
          "}";
        m.f.contentDocument.head.appendChild(st);
        // The 100% height must reach the phone: some pages wrap it in divs
        // with no height, and a percentage against an undefined height
        // collapses. Stretch the ancestors of every phone.
        m.f.contentDocument.querySelectorAll(SEL).forEach(function (tel) {
          var a = tel.parentElement;
          while (a && a !== m.f.contentDocument.body) {
            a.style.height = "100%";
            a.style.minHeight = "0";
            a.style.width = "100%";
            a = a.parentElement;
          }
        });
        if (conErrores) m.f.contentDocument.body.classList.add("mostrar-errores");
        if (oscuro) m.f.contentDocument.body.classList.add("modo-oscuro");
        // Focus often ends up inside the iframe: the arrows navigate from
        // there too.
        m.f.contentDocument.addEventListener("keydown", alTeclado);
        // Mockup buttons really navigate: data-ir="N" jumps to screen N of
        // this flow, data-ir="+1" closes the flow and moves to the next one.
        m.f.contentDocument.querySelectorAll("[data-ir]").forEach(function (b) {
          b.addEventListener("click", function () {
            var v = b.getAttribute("data-ir");
            if (v === "+1") { siguiente(1); return; }
            // "flow/N" jumps to screen N of ANOTHER flow.
            if (v.indexOf("/") > 0) {
              var partes = v.split("/");
              var destino = FLUJOS.findIndex(function (fl) {
                return fl.id === partes[0];
              });
              if (destino >= 0) mostrar(destino, parseInt(partes[1], 10));
              return;
            }
            mostrar(i, parseInt(v, 10));
          });
        });
        // The back arrow of each screen: undoes the real navigation
        // (history); with no path walked, falls to the previous step.
        m.f.contentDocument.querySelectorAll("[data-atras]").forEach(function (b) {
          b.addEventListener("click", atras);
        });
        m.cargado = true;
        m.pendientes.splice(0).forEach(function (cb) { cb(m); });
      });
      f.src = FLUJOS[i].src;
      lienzo.appendChild(f);
    }
    function telefonos(m) {
      return m.f.contentDocument.querySelectorAll(SEL);
    }
    // The screens of the linear walk. The ones marked data-alterna (a manual
    // form, a sheet, an error variant) are only reached by their buttons and
    // do not count as a step.
    function principales(m) {
      return [].filter.call(telefonos(m), function (t) {
        return !t.hasAttribute("data-alterna");
      });
    }
    // The unit that is shown and hidden: the phone with its wrappers. Some
    // pages wrap each phone in its own div; hiding only the phone left the
    // wrapper alive, and its gaps shifted the screen.
    function unidad(tel, doc) {
      var u = tel;
      while (
        u.parentElement &&
        u.parentElement !== doc.body &&
        u.parentElement.querySelectorAll(SEL).length === 1
      ) {
        u = u.parentElement;
      }
      return u;
    }
    function medir(m) {
      m.f.style.height = innerHeight + "px";
    }
    window.addEventListener("resize", function () {
      for (var j in marcos) medir(marcos[j]);
    });

    // Step label ("2/4", or the position borrowed by an alternate) and the
    // comment key of the visible screen. mostrar() sets them.
    var etiquetaPaso = "", claveVista = "";

    // Depth navigated in this session: each history entry carries it in its
    // state; with it, back knows whether there is somewhere to return to.
    var pilaN = (history.state && history.state.n) || 0;

    // raiz=true when the page comes from history (back/forward, reload, a
    // pasted hash): it paints without pushing another entry.
    function mostrar(i, p, raiz) {
      comentGuardarYa(); // what was written on the screen being left, safe
      flujo = i;
      marco(i, function (m) {
        var doc = m.f.contentDocument;
        var tels = telefonos(m);
        var prins = principales(m);
        if (p < 0) p = [].indexOf.call(tels, prins[prins.length - 1]);
        pantalla = Math.max(0, Math.min(p, tels.length - 1));
        var actual = tels[pantalla];
        tels.forEach(function (t, k) {
          unidad(t, doc).style.display = k === pantalla ? "" : "none";
        });
        for (var j in marcos) marcos[j].f.style.display = j == i ? "block" : "none";
        // Fonts and icons (CDN) arrive late: measure again a few times.
        medir(m);
        [300, 1000, 2500].forEach(function (ms) { setTimeout(function () { medir(m); }, ms); });
        window.scrollTo(0, 0);
        var pos = prins.indexOf(actual);
        etiquetaPaso = actual.dataset.paso
          ? actual.dataset.paso
          : prins.length > 1 && pos >= 0
          ? (pos + 1) + "/" + prins.length
          : "";
        claveVista = FLUJOS[i].titulo + (actual.dataset.clave
          ? " · " + actual.dataset.clave
          : etiquetaPaso && !actual.dataset.paso ? " · " + etiquetaPaso : "");
        // The step goes in the menu button; with no steps, the hamburger.
        menuBtn.innerHTML = etiquetaPaso
          ? '<span class="paso">' + etiquetaPaso + "</span>"
          : HAMBURGUESA;
        document.getElementById("lat-paso").textContent = etiquetaPaso;
        // The URL carries flow AND screen: a reload returns to this page.
        // Navigating PUSHES a real entry, so the browser back (and the one on
        // the screens) undoes the path walked.
        var url = "#" + FLUJOS[i].id + (pantalla > 0 ? "/" + pantalla : "");
        if (raiz || url === location.hash) {
          history.replaceState({ n: pilaN }, "", url);
        } else {
          history.pushState({ n: ++pilaN }, "", url);
        }
        pintarMenu();
        pintarLateral();
        comentCargar();
      });
    }

    function atras() {
      if (history.state && history.state.n > 0) { history.back(); return; }
      siguiente(-1);
    }

    function siguiente(paso) {
      marco(flujo, function (m) {
        var tels = telefonos(m);
        var prins = principales(m);
        var actual = tels[pantalla];
        var alterna = actual && actual.hasAttribute("data-alterna");
        // From an alternate, back returns to the screen that opened it.
        var padre = alterna
          ? parseInt(actual.getAttribute("data-padre") || "0", 10)
          : pantalla;
        if (alterna && paso < 0) { mostrar(flujo, padre); return; }
        var p = prins.indexOf(tels[padre]) + paso;
        if (p >= prins.length) mostrar((flujo + 1) % FLUJOS.length, 0);
        else if (p < 0) mostrar((flujo + FLUJOS.length - 1) % FLUJOS.length, -1);
        else mostrar(flujo, [].indexOf.call(tels, prins[p]));
      });
    }

    // ── Navigation: the floating menu (mobile) and the sidebar (desktop). ──
    function itemFlujo(fl, i, extra) {
      var b = document.createElement("button");
      b.type = "button";
      if (i < 9) {
        b.accessKey = String(i + 1);
        b.title = fl.titulo + " (accesskey " + (i + 1) + ")";
      } else {
        b.title = fl.titulo;
      }
      b.className = i === flujo ? "activo" : "";
      b.innerHTML =
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="6" y="2.5" width="12" height="19" rx="2.5"/><line x1="10.5" y1="18.5" x2="13.5" y2="18.5"/></svg>' +
        fl.titulo + (extra || "");
      b.addEventListener("click", function () {
        cerrarMenu();
        mostrar(i, 0);
      });
      if (!fl.spec) return b;
      // A flow with a spec gets a small link beside its button.
      var fila = document.createElement("div");
      fila.className = "fila";
      fila.appendChild(b);
      var a = document.createElement("a");
      a.className = "spec";
      a.href = fl.spec;
      a.target = "_blank";
      a.rel = "noopener";
      a.title = "Spec de " + fl.titulo;
      a.textContent = "Spec";
      fila.appendChild(a);
      return fila;
    }
    function botonErrores() {
      var b = document.createElement("button");
      b.type = "button";
      b.accessKey = "e";
      b.title = "Ver/ocultar validaciones (accesskey E)";
      b.className = conErrores ? "activo" : "";
      b.innerHTML =
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>' +
        (conErrores ? "Ocultar validaciones" : "Ver validaciones");
      b.addEventListener("click", alternarErrores);
      return b;
    }
    function botonOscuro() {
      var b = document.createElement("button");
      b.type = "button";
      b.accessKey = "o";
      b.title = "Tema claro/oscuro de los mockups (accesskey O)";
      b.className = oscuro ? "activo" : "";
      b.innerHTML = oscuro
        ? '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/></svg>Tema claro'
        : '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>Tema oscuro';
      b.addEventListener("click", alternarOscuro);
      return b;
    }
    function pintarMenu() {
      var cont = document.getElementById("menu-flujos");
      cont.innerHTML = "";
      FLUJOS.forEach(function (fl, i) { cont.appendChild(itemFlujo(fl, i)); });
      var raya = document.createElement("div");
      raya.className = "raya";
      cont.appendChild(raya);
      cont.appendChild(botonErrores());
      cont.appendChild(botonOscuro());
    }
    function pintarLateral() {
      var cont = document.getElementById("lateral-flujos");
      cont.innerHTML = "";
      FLUJOS.forEach(function (fl, i) {
        var extra = i === flujo && etiquetaPaso
          ? '<span class="paso-lateral">' + etiquetaPaso + "</span>"
          : "";
        cont.appendChild(itemFlujo(fl, i, extra));
      });
      var raya = document.createElement("div");
      raya.className = "raya";
      cont.appendChild(raya);
      cont.appendChild(botonErrores());
      cont.appendChild(botonOscuro());
    }
    // The "Web" group (desktop pages, then plain links) and the PDF link are
    // static: painted once, in the sidebar and in the mobile menu.
    function enlace(item, clase) {
      var a = document.createElement("a");
      if (clase) a.className = clase;
      a.href = item.href;
      a.target = "_blank";
      a.rel = "noopener";
      a.textContent = item.titulo;
      return a;
    }
    function pintarWeb() {
      var todos = WEB.concat(LINKS);
      var lat = document.getElementById("lateral-web");
      var mob = document.getElementById("menu-web");
      todos.forEach(function (it) {
        lat.appendChild(enlace(it, "pdf"));
        mob.appendChild(enlace(it));
      });
      document.getElementById("lateral-web-titulo").hidden = todos.length === 0;
      document.getElementById("menu-web-titulo").hidden = todos.length === 0;
      if (PDF) {
        ["lat-pdf", "menu-pdf", "menu-pdf-raya", "ayuda-pdf"].forEach(function (id) {
          document.getElementById(id).hidden = false;
        });
        document.getElementById("lat-pdf").href = PDF;
        document.getElementById("menu-pdf").href = PDF;
      }
      var n = Math.min(9, FLUJOS.length);
      document.getElementById("ayuda-n").textContent = String(n);
      document.getElementById("ayuda-flujos").hidden = n < 2;
    }
    function abrirMenu() {
      pintarMenu();
      menu.classList.add("abierto");
      coment.classList.add("abierto"); // the box of the current screen, too
      comentCargar();
      ubicarFlotantes();
      menuBtn.setAttribute("aria-expanded", "true");
    }
    function cerrarMenu() {
      if (esEscritorio.matches) return; // nothing to close on desktop
      comentGuardarYa();
      menu.classList.remove("abierto");
      coment.classList.remove("abierto");
      menuBtn.setAttribute("aria-expanded", "false");
    }
    // Menu and box stack against the buttons wherever they are: the box above
    // the buttons and the menu above the box (or below, against the top).
    function ubicarFlotantes() {
      if (esEscritorio.matches) return; // on desktop the box lives in the sidebar
      var r = fabs.getBoundingClientRect();
      function centrar(el) {
        var w = el.offsetWidth || 250;
        return Math.max(8, Math.min(r.left + r.width / 2 - w / 2, innerWidth - w - 8));
      }
      var ch = coment.offsetHeight || 130;
      var mh = menu.offsetHeight || 380;
      coment.style.left = centrar(coment) + "px";
      menu.style.left = centrar(menu) + "px";
      menu.style.transform = coment.style.transform = "none";
      menu.style.bottom = coment.style.bottom = "auto";
      if (r.top > ch + mh + 28) {
        coment.style.top = (r.top - ch - 12) + "px";
        menu.style.top = (r.top - ch - 12 - mh - 8) + "px";
      } else {
        coment.style.top = (r.bottom + 12) + "px";
        menu.style.top = (r.bottom + 12 + ch + 8) + "px";
      }
    }
    menuBtn.addEventListener("click", function () {
      menu.classList.contains("abierto") ? cerrarMenu() : abrirMenu();
    });

    // ── The comment box: small, for the screen being looked at. ────────────
    // One file (comentarios/index.md) with a `##` section per screen; the box
    // edits ONLY the section of the current screen and the save rebuilds the
    // whole file. The agent reads one file, and the reviewer writes two lines
    // without seeing a wall of markdown. The URL is relative to this page, so
    // it works at any mount (/mockups/comentarios/index or /comentarios/index).
    var coment = document.getElementById("coment");
    var comentTexto = document.getElementById("coment-texto");
    var comentClave = document.getElementById("coment-clave");
    var comentEstado = document.getElementById("coment-estado");
    var API = new URL("comentarios/index", location.href).href;
    var PREAMBULO =
      "# Comentarios · " + TITULO + "\n\n" +
      "<!-- Escribí tu comentario debajo de cada título. Se guarda solo. -->\n";
    var secciones = null; // [{clave, texto}] in file order
    var preambulo = PREAMBULO;
    var claveActual = null;
    var timerGuardar = null;
    var cargando = null;

    function parsear(md) {
      var partes = md.split(/^## +(.+)$/m);
      preambulo = partes[0].replace(/\s+$/, "") + "\n";
      secciones = [];
      for (var i = 1; i < partes.length; i += 2) {
        secciones.push({
          clave: partes[i].trim(),
          texto: (partes[i + 1] || "").replace(/^\n+|\s+$/g, ""),
        });
      }
    }
    function armar() {
      var md = preambulo;
      secciones.forEach(function (s) {
        md += "\n## " + s.clave + "\n";
        if (s.texto) md += "\n" + s.texto + "\n";
      });
      return md;
    }
    function seccion(clave) {
      for (var i = 0; i < secciones.length; i++) {
        if (secciones[i].clave === clave) return secciones[i];
      }
      var s = { clave: clave, texto: "" };
      secciones.push(s);
      return s;
    }
    function comentCargar() {
      if (!coment.classList.contains("abierto") && !esEscritorio.matches) return;
      if (!cargando) {
        // Never from the HTTP cache: a stale copy would be written back over
        // comments saved since.
        cargando = fetch(API, { cache: "no-store" })
          .then(function (r) { return r.ok ? r.text() : ""; })
          .then(function (md) { parsear(md && md.trim() ? md : PREAMBULO); })
          .catch(function () { parsear(PREAMBULO); });
      }
      cargando.then(function () {
        claveActual = claveVista;
        comentClave.textContent = claveActual;
        comentTexto.value = seccion(claveActual).texto;
        comentEstado.textContent = "";
      });
    }
    function comentGuardarYa() {
      clearTimeout(timerGuardar);
      if (secciones === null || claveActual === null) return;
      var s = seccion(claveActual);
      if (s.texto === comentTexto.value.trim()) return;
      s.texto = comentTexto.value.trim();
      comentEstado.textContent = "guardando…";
      fetch(API, {
        method: "PUT",
        headers: { "Content-Type": "text/plain; charset=utf-8" },
        body: armar(),
        keepalive: true,
      })
        .then(function (r) { comentEstado.textContent = r.ok ? "guardado ✓" : "error al guardar"; })
        .catch(function () { comentEstado.textContent = "sin conexión"; });
    }
    comentTexto.addEventListener("input", function () {
      comentEstado.textContent = "guardando…";
      clearTimeout(timerGuardar);
      timerGuardar = setTimeout(comentGuardarYa, 700);
    });
    addEventListener("pagehide", comentGuardarYa);
    document.addEventListener("visibilitychange", function () {
      if (document.visibilityState === "hidden") comentGuardarYa();
    });
    // On desktop the box goes inside the sidebar and is always open.
    function acomodarComent() {
      if (esEscritorio.matches) {
        document.getElementById("coment-lateral").appendChild(coment);
        coment.classList.add("abierto");
        comentCargar();
      } else {
        document.body.appendChild(coment);
        coment.classList.remove("abierto");
      }
    }
    esEscritorio.addEventListener("change", acomodarComent);

    document.getElementById("atras").addEventListener("click", function () { siguiente(-1); });
    document.getElementById("siguiente").addEventListener("click", function () { siguiente(1); });
    document.getElementById("lat-atras").addEventListener("click", function () { siguiente(-1); });
    document.getElementById("lat-sig").addEventListener("click", function () { siguiente(1); });
    // Taps the primary button (Continuar) of the visible screen.
    function accionPrincipal() {
      marco(flujo, function (m) {
        var tels = telefonos(m);
        var actual = tels[pantalla];
        if (!actual) return;
        var u = unidad(actual, m.f.contentDocument);
        var b = u.querySelector(".cta-shadow[data-ir]") || u.querySelector("[data-ir]");
        if (b) b.click();
      });
    }
    // Keyboard shortcuts (not while typing in a field):
    //   ← / →  previous / next            Enter      Continuar of the screen
    //   ⌫      back (like the arrow)      E          show/hide errors
    //   1–9    jump to a flow             C          comment this screen
    //   M      menu (mobile)              D          download the PDF
    function alTeclado(e) {
      // With a modifier it is not ours: Cmd+C copies, the browser handles
      // the accesskeys by itself.
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      var t = e.target;
      if (t && (t.tagName === "INPUT" || t.tagName === "TEXTAREA")) {
        if (e.key === "Escape") { t.blur(); cerrarMenu(); }
        return; // typing does not navigate
      }
      var k = e.key.toLowerCase();
      var ayuda = document.getElementById("ayuda");
      if (e.key === "?") { ayuda.classList.toggle("abierto"); return; }
      if (e.key === "Escape" && ayuda.classList.contains("abierto")) {
        ayuda.classList.remove("abierto");
        return;
      }
      if (e.key === "ArrowRight") siguiente(1);
      else if (e.key === "ArrowLeft") siguiente(-1);
      else if (e.key === "Backspace") { e.preventDefault(); atras(); }
      else if (e.key === "Enter") accionPrincipal();
      else if (e.key === "Escape") cerrarMenu();
      else if (k === "e") alternarErrores();
      else if (k === "o") alternarOscuro();
      else if (k === "m") {
        menu.classList.contains("abierto") ? cerrarMenu() : abrirMenu();
      } else if (k === "c") {
        if (!esEscritorio.matches && !coment.classList.contains("abierto")) {
          abrirMenu();
        }
        comentTexto.focus();
      } else if (k === "d") {
        if (PDF) window.open(PDF, "_blank", "noopener");
      } else if (/^[1-9]$/.test(k) && parseInt(k, 10) <= FLUJOS.length) {
        mostrar(parseInt(k, 10) - 1, 0);
      }
    }
    document.addEventListener("keydown", alTeclado);
    document.getElementById("ayuda").addEventListener("click", function (e) {
      if (e.target === this) this.classList.remove("abierto");
    });

    // ── Moving the buttons: press and hold (~300 ms), then drag. ────────────
    // A short tap is still a tap; moving before the delay also cancels it (a
    // scroll or an imprecise finger, not an intention to move). The position
    // is kept for the next visit.
    var timerAgarre = null, arrastrando = false, recienArrastrado = false;
    var pIni = null, esquina = null;
    var fraccion = null; // [0..1, 0..1] inside the usable window area
    function colocar(x, y) {
      var r = fabs.getBoundingClientRect();
      var maxX = Math.max(6, innerWidth - r.width - 6);
      var maxY = Math.max(6, innerHeight - r.height - 6);
      x = Math.max(6, Math.min(x, maxX));
      y = Math.max(6, Math.min(y, maxY));
      fabs.style.left = x + "px";
      fabs.style.top = y + "px";
      fabs.style.bottom = "auto";
      fabs.style.transform = "none";
      fraccion = [
        maxX > 6 ? (x - 6) / (maxX - 6) : 0,
        maxY > 6 ? (y - 6) / (maxY - 6) : 0,
      ];
    }
    function reColocar() {
      if (!fraccion) return;
      var f = fraccion;
      var r = fabs.getBoundingClientRect();
      var maxX = Math.max(6, innerWidth - r.width - 6);
      var maxY = Math.max(6, innerHeight - r.height - 6);
      colocar(6 + f[0] * (maxX - 6), 6 + f[1] * (maxY - 6));
    }
    try {
      var guardada = JSON.parse(
        localStorage.getItem("mockups-fabs-frac") || "null"
      );
      if (guardada) { fraccion = guardada; reColocar(); }
    } catch (e) { /* no storage: the usual place */ }
    fabs.addEventListener("pointerdown", function (e) {
      var r = fabs.getBoundingClientRect();
      pIni = { x: e.clientX, y: e.clientY, id: e.pointerId };
      esquina = { x: r.left, y: r.top };
      clearTimeout(timerAgarre);
      timerAgarre = setTimeout(function () {
        arrastrando = true;
        fabs.classList.add("arrastrando");
        try { fabs.setPointerCapture(pIni.id); } catch (err) { /* already released */ }
      }, 300);
    });
    fabs.addEventListener("pointermove", function (e) {
      if (!pIni) return;
      if (!arrastrando) {
        if (Math.abs(e.clientX - pIni.x) > 8 || Math.abs(e.clientY - pIni.y) > 8) {
          clearTimeout(timerAgarre);
        }
        return;
      }
      recienArrastrado = true;
      colocar(esquina.x + e.clientX - pIni.x, esquina.y + e.clientY - pIni.y);
      if (menu.classList.contains("abierto")) ubicarFlotantes();
    });
    function soltarAgarre() {
      clearTimeout(timerAgarre);
      pIni = null;
      if (!arrastrando) return;
      arrastrando = false;
      fabs.classList.remove("arrastrando");
      try {
        localStorage.setItem("mockups-fabs-frac", JSON.stringify(fraccion));
      } catch (e) { /* no storage */ }
    }
    fabs.addEventListener("pointerup", soltarAgarre);
    fabs.addEventListener("pointercancel", soltarAgarre);
    // The click that follows a drag must not press any button.
    fabs.addEventListener("click", function (e) {
      if (recienArrastrado) {
        recienArrastrado = false;
        e.preventDefault();
        e.stopImmediatePropagation();
      }
    }, true);
    fabs.addEventListener("contextmenu", function (e) { e.preventDefault(); });
    window.addEventListener("resize", reColocar);

    pintarWeb();
    acomodarComent();
    function irPorHash() {
      var m = location.hash.match(/^#([\w-]+)(?:\/(\d+))?$/);
      var i = m
        ? FLUJOS.findIndex(function (fl) { return fl.id === m[1]; })
        : -1;
      pilaN = (history.state && history.state.n) || 0;
      mostrar(i < 0 ? 0 : i, m && m[2] ? parseInt(m[2], 10) : 0, true);
    }
    // Browser back/forward (and pasting a hash) also navigate.
    window.addEventListener("hashchange", irPorHash);
    irPorHash();
  }
})();
</script>
</body></html>
''';
