import 'dart:io';

/// Copies `viewer/index.html` into `lib/src/viewer_html.dart` as a Dart
/// string, so the viewer ships inside the package with no asset lookup.
///
/// Run from the package directory: `dart run tool/embed.dart`.
/// A test checks that the two files are in sync.
void main() {
  final root = File.fromUri(Platform.script).parent.parent;
  final source = File('${root.path}/viewer/index.html');
  final target = File('${root.path}/lib/src/viewer_html.dart');
  final html = source.readAsStringSync();
  if (html.contains("'''")) {
    stderr.writeln(
      "viewer/index.html must not contain ''' (raw string delimiter)",
    );
    exit(1);
  }
  target.writeAsStringSync(
    '// GENERATED by tool/embed.dart from viewer/index.html. Do not edit.\n'
    '// Run `dart run tool/embed.dart` after changing the viewer.\n'
    '\n'
    '/// The viewer page, as shipped.\n'
    "const String viewerHtml = r'''\n"
    '$html'
    "''';\n",
  );
  stdout.writeln('wrote ${target.path} (${html.length} chars)');
}
